### ISSUE TITLE
Running judge with `jpm test` fails on missing test directory

### ISSUE THREAD

**Issue by stefanvanburen** [ianthehenry/judge#11]
Hi, thanks for the great tool and Janet resources.

Trying out using `judge` and works great! The only issue I ran into was using the suggestion from the README:

> You can also add this to your project.janet file:
> `(task "test" [] (shell "jpm_tree/bin/judge"))`
> To run Judge with a normal jpm test invocation.

I've tried that in a simple project with the tests inlined in the top-level janet file, tree structure like:

```
.
├── project.janet
└── projecteuler.janet
```

project.janet:
```janet
(declare-project
  :name "projecteuler"
  :dependencies ["judge"])

(task "test" [] (shell "jpm_tree/bin/judge"))
```

Running `jpm test`:

```console
$ jpm test
error: cannot open directory test: No such file or directory
error: build fail
  in pdag [/opt/homebrew/lib/janet/jpm/dagbuild.janet] (tail call) on line 79, column 23
  in run-main [boot.janet] on line 4432, column 16
  in cli-main [boot.janet] on line 4613, column 17
```

Not sure on the internals of jpm, but it doesn't seem to like that the `test/` directory doesn't exist. If I even just `mkdir test/`, it'll work (it seemingly still looks at the `test/` directory and immediately passes everything):

```
$ mkdir test/
$ jpm test
All tests passed.
# projecteuler.janet

4 passed
```

Ideally, would not need to create the empty `test/` dir to use the task override.

If it matters:

```
$ janet -v
1.36.0-homebrew
```

**Comment by ianthehenry** [comment]
Oh interesting. I feel like this is kind of a bug in `jpm`? Although really I have never used `jpm test` and think maybe I should just remove this from the readme. I think it's better to add `./jpm_tree/bin` to `PATH` and invoke judge as `judge` so that you can use `judge -i`, `judge -a`, etc. The only real reason I can think of to run it as part of `jpm test` is like if you already have a CI or something that's doing that? I dunno.

**Comment by stefanvanburen** [comment]
> think maybe I should just remove this from the readme.

Took a swing at this in #12. Not sure if it's worth reporting to jpm upstream, relatively unfamiliar with tasks in jpm :).
