### ISSUE TITLE
[2.0.0+] Inline Tests Run Repeatedly if File is `import`ed with Working Directory Import Style

### ISSUE THREAD

**Issue by CFiggers** [ianthehenry/judge#3]
Since Janet 1.14.1, Janet has supported [Working Directory Imports](https://janet-lang.org/docs/modules.html#Working-Directory-Imports).

It appears that if a test is defined inline inside of a source file, when that file is `use`ed or `import`ed elsewhere in the project using the Working Directory Import style (i.e. the import begins with a `/`) the test is detected more than once and run repeatedly.

**To Replicate:**

In a fresh project, create a file to be imported.

```janet
# to-import.janet

(use judge)

(defn imported-function [& args]
  (+ 1 1))

(deftest imported-function
  (test (import-function) 2))
```

Create a file that imports the other file:

```janet
# main.janet

(import /to-import)

(defn main [& args]
  (print "Hello, world"))

```

Run judge:

```bash
$ judge
running test: imported-function
running test: imported-function
2 passed 0 failed 0 skipped 0 unreachable
```

This seems to be handled for when using _relative_ imports:

```janet
# main.janet

#       v
(import ./to-import)

(defn main [& args]
  (print "Hello, world"))

```

```bash
$ judge
running test: imported-function
1 passed 0 failed 0 skipped 0 unreachable
```

**Comment by ianthehenry** [comment]
Oh hey! Thanks for the repro. It looks the module cache key is different for `/relative` imports? Very interesting.

I *think* I've fixed this in e95636461abd6f8c10d5ddf73df762ca4f9c598f. As a side effect you can no longer pass absolute file paths to the Judge test runner, but I think that's basically fine? I could try to support that as well, but they would exhibit this same problem of entering the module cache with a different key.

Could you let me know if that works?

**Comment by CFiggers** [comment]
That seems to have fixed it for me! Thanks for the super quick turn-around.

I haven't tried passing file paths to the judge test runner yet, so I wouldn't notice the difference at all from losing absolute paths. :)

**Comment by ianthehenry** [comment]
Hmm, actually we can still allow absolute paths, which might be useful for editor tooling. But mixing absolute and relative paths will cause tests to run multiple times (Judge just uses the Janet module cache to ensure that files are only run once). I added some more tests to demonstrate potential issues in aed738a7a7c70c983be9279e9e88aa00359fd629
